"""Internal deterministic core for sdd-workflow."""

from .diagnostics import Diagnostic, Severity
from .doctor import DoctorFinding, diagnose_project
from .active_metadata import (
    METADATA_VERSION,
    ActiveMetadata,
    ActiveMetadataError,
    parse_active_metadata,
    serialize_active_metadata,
)
from .managed_state import (
    ATTESTATION_VERSION,
    ManagedStateError,
    compare_attested_state,
    create_attestation,
    project_managed_state,
    validate_attestation,
)
from .atomic_write import atomic_replace_bytes
from .archive_model import (
    ARCHIVE_MODEL_VERSION,
    ArchiveDiagnostic,
    ArchiveRecord,
    ArchiveScan,
    load_legacy_archive_records,
    load_archive_records,
    parse_legacy_index,
)
from .archive_index import (
    IndexDifference,
    rebuild_archive_index,
    render_archive_index,
    replace_archive_index,
    validate_archive_index,
)
from .approval import (
    APPROVAL_MODEL_VERSION,
    ApprovalDifference,
    ApprovalManifest,
    ApprovalManifestError,
    approval_manifest_sha256,
    compare_approval_manifests,
    load_approval_manifest,
    parse_approval_manifest,
    project_approval_manifest,
    serialize_approval_manifest,
)
from .discovery import (
    ProjectDiscoveryError,
    ProjectRoot,
    ProposalPathError,
    ProposalPaths,
    RootSource,
    SHORT_NAME_PATTERN,
    discover_project_root,
    list_active_proposal_paths,
    resolve_proposal_paths,
    validate_short_name,
)
from .model import (
    CANONICAL_MODEL_VERSION,
    CANONICAL_FIELD_APPROVAL_POLICY,
    CANONICAL_EXTENSION_APPROVAL_POLICY,
    CANONICAL_SECTION_APPROVAL_POLICY,
    ApprovalRelevance,
    CanonicalExtension,
    CanonicalProposal,
    CanonicalSection,
    CanonicalTask,
    ParseOutcome,
    TaskScanResult,
)
from .parser_v1 import (
    SUPPORTED_SCHEMA_VERSIONS,
    SchemaSelection,
    detect_schema_version,
    parse_v1,
    parse_with_schema,
    select_schema_from_document,
)
from .parser_legacy import LEGACY_MUTATION_BLOCK_CODE, parse_legacy
from .parser_v2 import VALID_V2_CHANGE_TYPES, parse_v2
from .scanner import ACCEPTANCE_HEADING, scan_tasks
from .snapshot import (
    SNAPSHOT_VERSION,
    SnapshotManifest,
    build_snapshot,
    canonical_snapshot_payload,
)
from .transitions import (
    CompleteTaskValidation,
    TransitionError,
    TransitionResult,
    approve_proposal,
    begin_revision,
    complete_task,
    replace_status,
    validate_complete_task,
)
from .task_identity import task_digest
from .summary_input import (
    SUMMARY_MAX_BYTES,
    SummaryInputError,
    fold_summary_for_index,
    read_summary,
)
from .terminal_transitions import (
    TerminalCommitResult,
    TerminalValidation,
    commit_terminal_transition,
    find_committed_terminal_retry,
    resume_staged_terminal_transition,
    validate_abandon,
    validate_archive,
)
from .version import ENGINE_VERSION, engine_generation, parse_engine_version

__all__ = [
    "APPROVAL_MODEL_VERSION",
    "ATTESTATION_VERSION",
    "ARCHIVE_MODEL_VERSION",
    "METADATA_VERSION",
    "ENGINE_VERSION",
    "CANONICAL_MODEL_VERSION",
    "CANONICAL_FIELD_APPROVAL_POLICY",
    "CANONICAL_EXTENSION_APPROVAL_POLICY",
    "CANONICAL_SECTION_APPROVAL_POLICY",
    "ApprovalDifference",
    "ArchiveDiagnostic",
    "ArchiveRecord",
    "ArchiveScan",
    "ActiveMetadata",
    "ActiveMetadataError",
    "ApprovalManifest",
    "ApprovalManifestError",
    "ApprovalRelevance",
    "ACCEPTANCE_HEADING",
    "CanonicalExtension",
    "CanonicalProposal",
    "CanonicalSection",
    "CanonicalTask",
    "CompleteTaskValidation",
    "ManagedStateError",
    "IndexDifference",
    "Diagnostic",
    "DoctorFinding",
    "LEGACY_MUTATION_BLOCK_CODE",
    "ParseOutcome",
    "ProjectDiscoveryError",
    "ProjectRoot",
    "ProposalPathError",
    "ProposalPaths",
    "RootSource",
    "SHORT_NAME_PATTERN",
    "SNAPSHOT_VERSION",
    "SUMMARY_MAX_BYTES",
    "Severity",
    "SnapshotManifest",
    "SUPPORTED_SCHEMA_VERSIONS",
    "VALID_V2_CHANGE_TYPES",
    "SchemaSelection",
    "TaskScanResult",
    "SummaryInputError",
    "TransitionError",
    "TransitionResult",
    "TerminalValidation",
    "TerminalCommitResult",
    "detect_schema_version",
    "discover_project_root",
    "diagnose_project",
    "list_active_proposal_paths",
    "load_legacy_archive_records",
    "load_archive_records",
    "parse_v1",
    "parse_v2",
    "parse_legacy",
    "parse_with_schema",
    "select_schema_from_document",
    "resolve_proposal_paths",
    "scan_tasks",
    "build_snapshot",
    "canonical_snapshot_payload",
    "validate_short_name",
    "task_digest",
    "fold_summary_for_index",
    "read_summary",
    "approval_manifest_sha256",
    "compare_approval_manifests",
    "load_approval_manifest",
    "parse_approval_manifest",
    "project_approval_manifest",
    "serialize_approval_manifest",
    "approve_proposal",
    "begin_revision",
    "complete_task",
    "compare_attested_state",
    "create_attestation",
    "atomic_replace_bytes",
    "parse_active_metadata",
    "parse_legacy_index",
    "project_managed_state",
    "replace_status",
    "render_archive_index",
    "replace_archive_index",
    "rebuild_archive_index",
    "serialize_active_metadata",
    "validate_complete_task",
    "validate_attestation",
    "validate_archive_index",
    "validate_archive",
    "validate_abandon",
    "commit_terminal_transition",
    "find_committed_terminal_retry",
    "resume_staged_terminal_transition",
    "engine_generation",
    "parse_engine_version",
]
