#!/usr/bin/env python3
"""Entry point for the sdd-workflow deterministic core."""

from __future__ import annotations

import sys


MINIMUM_PYTHON = (3, 11)

# Installed skills may be symlinked back to a maintained source tree. Keep every
# readonly CLI invocation from depositing generated bytecode in that package.
sys.dont_write_bytecode = True


if sys.version_info < MINIMUM_PYTHON:
    required = ".".join(str(part) for part in MINIMUM_PYTHON)
    current = ".".join(str(part) for part in sys.version_info[:3])
    sys.stderr.write(
        "ERROR_PYTHON_VERSION: sdd-workflow requires Python "
        f"{required} or newer (found {current}). Install a supported Python "
        "and rerun this command; do not fall back to prose parsing.\n"
    )
    raise SystemExit(1)


from sdd_core.cli import main  # noqa: E402


if __name__ == "__main__":
    raise SystemExit(main())
